version: '2'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movies
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
  perl:
    build: .
    links:
      - db
    volumes: 
      - ./web/:/var/www/
      - ./.log/web/:/var/log/httpd/
    ports:
      - 8080:80 